#!/system/bin/sh
exec >"/data/local/tmp/${0##*/}.log" 2>&1

log() {
  local message="${1}"

  echo >&2 "`date +%Y-%m-%d@%H:%M:%S` ${message}"
}

hostCommand() {
# log "host command: ${*}"
  "${@}"
}

sqlCommand() {
  local command="${1}"

  hostCommand sqlite3 "/data/data/com.android.providers.settings/databases/settings.db" "${command}"
}

getField() {
  local table="${1}"
  local name="${2}"

  sqlCommand "select value from ${table} where name=\"${name}\""
}

setField() {
  local table="${1}"
  local name="${2}"
  local value="${3}"

  log "checking field: ${table}.${name} = ${value}"
  [ "$(getField "${table}" "${name}")" = "${value}" ] || {
    log "setting field: ${table}.${name} = ${value}"
    sqlCommand "insert into ${table} (name, value) values (\"${name}\", \"${value}\")"
  }
}

getProperty() {
  local name="${1}"

  hostCommand getprop "${name}"
}

setProperty() {
  local name="${1}"
  local value="${2}"

  log "checking property: ${name} = ${value}"
  [ "$(getProperty "${name}")" = "${value}" ] || {
    log "setting property: ${name} = ${value}"
    hostCommand setprop "${name}" "${value}"
  }
}

permitEventDevice() {
  local identifier="${1}"
  set -- `ls /sys/bus/platform/devices/${identifier}/input*`

  [ "${#}" -eq 1 ] && {
    local name="${1##*/}"
    local event="${name#input}"

    [ -n "${event}" ] && {
      local device="/dev/input/event${event}"
      log "permitting event device: ${device} (${identifier})"
      hostCommand chmod 666 "${device}"
    }
  }
}

# enable ADB (the Android Debug Bridge)
setProperty persist.service.adb.enable 1
setField secure adb_enabled 1

# enable power switch monitoring
permitEventDevice twl4030_pwrbutton

# enable keyboard monitoring
permitEventDevice cp430_keypad

# enable key event injection
chmod 666 /dev/uinput

# enable the braille device
chmod 666 /dev/braille0

# disable scren locking
setField secure lockscreen.disabled 1

# set the screen off timeout to 30 minutes (in milliseconds)
setField system screen_off_timeout 1800000

# enable the installation of packages from foreign sources
setField secure install_non_market_apps 1

# enable the developer settings screen
setField secure development_settings_enabled 1

# enable accessibility services
setField secure accessibility_enabled 1

# wait for booting to finish
log "waiting for boot to complete"
while [ "`getprop sys.boot_completed`" != "1" ]
do
  sleep 5
done
log "boot completed"

log "setting input method"
package="org.nbp.b2g.ui"
component="${package}/.InputService"
hostCommand ime enable "${component}" &&
hostCommand ime set "${component}"

log "done"
exit 0
