#!/system/bin/sh

setField() {
   local table="${1}"
   local name="${2}"
   local value="${3}"

   sqlite3 "/data/data/com.android.providers.settings/databases/settings.db" "insert into ${table} (name, value) values (\"${name}\", \"${value}\")"
}

setProperty() {
   local name="${1}"
   local value="${2}"

   setprop "${name}" "${value}"
}

permitEventDevice() {
   set -- `ls /sys/bus/platform/devices/${1}/input*`

   [ "${#}" -eq 1 ] && {
      local name="${1##*/}"
      local event="${name#input}"

      [ -n "${event}" ] && {
         local device="/dev/input/event${event}"
         chmod 666 "${device}"
      }
   }
}

# enable ADB (the Android Debug Bridge)
setProperty persist.service.adb.enable 1
setField secure adb_enabled 1

# enable power switch monitoring
permitEventDevice twl4030_pwrbutton

# enable keyboard monitoring
permitEventDevice cp430_keypad

# enable key event injection
chmod 666 /dev/uinput

# enable the braille device
chmod 666 /dev/braille0

# disable scren locking
setField secure lockscreen.disabled 1

# set the screen off timeout to 30 minutes (in milliseconds)
setField system screen_off_timeout 1800000

# enable the installation of packages from foreign sources
setField secure install_non_market_apps 1

# enable the developer settings screen
setField secure development_settings_enabled 1

# enable accessibility services
setField secure accessibility_enabled 1

# enable the B2G input service
package="org.nbp.b2g.ui"
component="${package}/.InputService"
ime enable "${component}" && ime set "${component}"

exit 0
