include ../setup.mk
include $(BUILD_DIRECTORY)app.prologue.mk
include $(BUILD_DIRECTORY)app.properties.mk

APPLICATION_NAME = NBP_Navigator
PACKAGE_PATH = org.nbp.navigator

include $(BUILD_DIRECTORY)app.epilogue.mk
