SIGNING_PROPERTIES_FILE = signing.properties
ANDROID_BUILD_MODE := $(strip $(if $(wildcard $(SIGNING_PROPERTIES_FILE)), release, debug))
show-build-mode:
	@echo $(ANDROID_BUILD_MODE)

ANDROID_JNI_SOURCES := $(JNI_SOURCES:%=$(ANDROID_JNI_DIRECTORY)/%)
ANDROID_NATIVE_LIBRARY = $(ANDROID_PLATFORM_DIRECTORY)/lib$(APPLICATION_NAME).so
jni: $(ANDROID_NATIVE_LIBRARY)
$(ANDROID_NATIVE_LIBRARY): $(ANDROID_JNI_SOURCES)
	ndk-build

ANDROID_PROJECT_PACKAGE = $(ANDROID_BINARIES_DIRECTORY)/$(APPLICATION_NAME)-$(ANDROID_BUILD_MODE).apk
apk: $(ANDROID_PROJECT_PACKAGE)
$(ANDROID_PROJECT_PACKAGE): jni $(ANDROID_LOCAL_FILES) AndroidManifest.xml
	ant $(ANDROID_BUILD_MODE)

clean::
	-rm -f $(ANDROID_LOCAL_FILES)
	-rm -f -r $(ANDROID_BINARIES_DIRECTORY)
	-rm -f -r $(ANDROID_PLATFORM_DIRECTORY)
	-rm -f -r gen
	-rm -f -r obj

install: all
	adb install $(ANDROID_PROJECT_PACKAGE)

reinstall: all
	adb install -r $(ANDROID_PROJECT_PACKAGE)

uninstall:
	adb uninstall $(PACKAGE_PATH)

FORCE:

