include ../setup.mk
include $(TOP)app.prologue.mk
include $(TOP)app.properties.mk

APPLICATION_NAME = NBP_Compass
PACKAGE_PATH = org.nbp.compass
PLATFORM_NAME = armeabi

include $(TOP)app.epilogue.mk
