include ../setup.mk
include $(BUILD_DIRECTORY)app.prologue.mk
include $(BUILD_DIRECTORY)app.properties.mk

APPLICATION_NAME = NBP_Compass
PACKAGE_PATH = org.nbp.compass

include $(BUILD_DIRECTORY)app.epilogue.mk
