include ../../setup.mk
include $(BUILD_DIRECTORY)app.prologue.mk
include $(BUILD_DIRECTORY)app.properties.mk

APPLICATION_NAME = NBP_IPAWS
PACKAGE_PATH = org.nbp.ipaws

include $(BUILD_DIRECTORY)app.epilogue.mk
