#!/bin/sh
set -e

. ../../build/resources.sh
writeResourcesPrologue

sed -n '
  s/^\.\.  *|\([a-zA-Z]*\)|  *replace::  *\(.*\)$/\1 \2/
  T

  s/ *$//
  s/ `/ /g
  s/`_//g
  s/|product name|/B2G/
  s/|organization acronym|/NBP/

  p
' <../doc/UserInterface/Reference/actions.rst |
  while read action description
  do
    writeSimpleResource string "action_summary_${action}" "${description}"
  done

writeResourcesEpilogue
exit 0
