#!/bin/sh
set -e

xmlVersion="1.0"
xmlEncoding="utf-8"

printHeader() {
  echo "<?xml version=\"${xmlVersion}\" encoding=\"${xmlEncoding}\" ?>"
  echo ""
  echo "<resources>"
}

printFooter() {
  echo "</resources>"
}

printProperty() {
  local type="${1}"
  local name="${2}"
  local value="${3}"

  echo "  <${type} name=\"${name}\">${value}</${type}>"
}

. ../../properties.sh

printHeader
printProperty integer app_version_code "$(printf "0x%02X%02X%04X" "${versionMajor}" "${versionMinor}" "${revisionIncrement}")"
printProperty string app_version_name "${packageVersion}"
printProperty string app_source_revision "${sourceRevision}"
printProperty string app_build_time "${buildDate}@${buildTime} ${buildZone}"
printFooter

exit 0
