#!/bin/sh
set -e

. ../../properties.sh
. ../../resources.sh

printResourcesPrologue
printSimpleResource integer app_version_code "${versionCode}"
printSimpleResource string app_version_name "${versionNumber}"
printSimpleResource string app_source_revision "${sourceRevision}"
printSimpleResource string app_build_time "${buildDate}@${buildTime} ${buildZone}"
printResourcesEpilogue

exit 0
