#!/bin/sh
set -e

tagPrefix="B2G_UI"
xmlVersion="1.0"
xmlEncoding="utf-8"

printHeader() {
  printf "<?xml version=\"%s\" encoding=\"%s\" ?>\\n\\n" "${xmlVersion}" "${xmlEncoding}"
  printf "<resources>\\n"
}

printFooter() {
  printf "</resources>\\n"
}

printResource() {
  local type="${1}"
  local name="${2}"
  local format="${3}"
  shift 3

  printf "  <${type} name=\"${name}\">${format}</${type}>\\n" "${@}"
}

revision="$(git describe --long --tags --match "${tagPrefix}-*")"
set -- ${revision//-/ }
version="${2}"
incredment="${3}"

set -- ${version//./ }
major="${1}"
minor="${2}"

printHeader
printResource string app_version_name "%d.%d.%d" "${major}" "${minor}" "${incredment}"
printResource integer app_version_code "0x%02X%02X%04X" "${major}" "${minor}" "${incredment}"
printFooter

exit 0
