#!/bin/sh
set -e

tagPrefix="B2G_UI"
xmlVersion="1.0"
xmlEncoding="utf-8"

printHeader() {
  printf "<?xml version=\"%s\" encoding=\"%s\" ?>\\n\\n" "${xmlVersion}" "${xmlEncoding}"
  printf "<resources>\\n"
}

printFooter() {
  printf "</resources>\\n"
}

printResource() {
  local type="${1}"
  local name="${2}"
  local format="${3}"
  shift 3

  printf "  <${type} name=\"${name}\">${format}</${type}>\\n" "${@}"
}

revisionIdentifier="$(git describe --long --tags --abbrev=16 --match "${tagPrefix}-*")"
set -- ${revisionIdentifier//-/ }
revisionVersion="${2}"
revisionIncrement="${3}"
revisionCommit="${4#g}"

set -- ${revisionVersion//./ }
versionMajor="${1}"
versionMinor="${2}"

printHeader
printResource string app_version_name "%d.%d.%d" "${versionMajor}" "${versionMinor}" "${revisionIncrement}"
printResource integer app_version_code "0x%02X%02X%04X" "${versionMajor}" "${versionMinor}" "${revisionIncrement}"
printResource string app_source_revision "git:%s" "${revisionCommit}"
printResource string app_build_time "%s" "$(date --utc +'%Y-%m-%d@%H:%M %Z')"
printFooter

exit 0
