include ../setup.mk
include $(BUILD_DIRECTORY)app.prologue.mk
include $(BUILD_DIRECTORY)app.properties.mk

APPLICATION_NAME = NBP_Calculator
PACKAGE_PATH = org.nbp.calculator

include $(BUILD_DIRECTORY)app.epilogue.mk
