include ../setup.mk
include $(TOP)app.prologue.mk
include $(TOP)app.properties.mk

APPLICATION_NAME = NBP_Calculator
PACKAGE_PATH = org.nbp.calculator
PLATFORM_NAME = armeabi

include $(TOP)app.epilogue.mk
