include ../setup.mk
include $(BUILD_DIRECTORY)app.prologue.mk
include $(BUILD_DIRECTORY)app.properties.mk

APPLICATION_NAME = NBP_Editor
PACKAGE_PATH = org.nbp.editor

include $(BUILD_DIRECTORY)app.epilogue.mk
