#!/usr/bin/sh

vtNumber=2

set -e
set +o monitor
umask 022
cd /

packageName="brltty"
systemDirectory="/etc/${packageName}"
persistentDirectory="/cache/${packageName}"
temporaryDirectory="/tmp/${packageName}"

programMessage() {
  local message="${1}"
  
  echo >&2 "${0##*/}: ${message}"
}

syntaxError() {
  local message="${1}"
  
  programMessage "${message}"
  exit 2
}

semanticError() {
  local message="${1}"
  
  programMessage "${message}"
  exit 3
}

checkProcess() {
  local file="${1}"

  [ ! -f "${file}" ] || {
    local pid="$(cat "${file}")"
    ! kill -0 "${pid}" 2>/dev/null || return 0
  }

  return 1
}

makeDirectory() {
  local directory="${1}"

  mkdir -p "${directory}" || exit 4
}

mountDirectory() {
  local directory="${1}"
  
  [ ! -d "${directory}" ] || {
    set -- $(ls "${directory}")
    [ "${#}" -gt 0 ] || shell mount "${directory}"
  }
}

makePersistentDirectory() {
  mountDirectory /cache
  makeDirectory "${persistentDirectory}"
  local from

  for from in "${systemDirectory}/Initial/"*
  do
    local to="${persistentDirectory}/${from##*/}"
    [ -f "${to}" ] || cp -a "${from}" "${to}"
  done
}

makeTemporaryDirectory() {
  makeDirectory "${temporaryDirectory}"
}

makeDirectories() {
  makePersistentDirectory
  makeTemporaryDirectory
}

startInteractiveShell() {
  local pidFile="${temporaryDirectory}/shell-${vtNumber}.pid"
  
  if checkProcess "${pidFile}"
  then
    programMessage "shell already running"
  else
    openvt -w -c "${vtNumber}" shell &
    echo $! >"${pidFile}"
    programMessage "shell started"
  fi
}

setBrailleParameters() {
  export BRLTTY_PID_FILE="${temporaryDirectory}/brltty.pid"
  export BRLTTY_LOG_FILE="${temporaryDirectory}/log"

  export BRLTTY_UPDATABLE_DIRECTORY="${persistentDirectory}"
  export BRLTTY_WRITABLE_DIRECTORY="${systemDirectory}/Writable"
  export BRLTTY_TABLES_DIRECTORY="${systemDirectory}"

  export BRLTTY_CONFIGURATION_FILE="${persistentDirectory}/config"
  export BRLTTY_PREFERENCES_FILE="prefs"

  export BRLTTY_SCREEN_DRIVER="lx"
  export BRLTTY_SCREEN_PARAMETERS="lx:vt=${vtNumber}"
}

readonly noMoreParameters='
  [ "${#}" -eq 0 ] || syntaxError "too many parameters"
'

performAction_start() {
  eval "${noMoreParameters}"

  makeDirectories
  startInteractiveShell
  setBrailleParameters

  if checkProcess "${BRLTTY_PID_FILE}"
  then
    programMessage "${packageName} already running"
  else
    cfg-sound -q
    brltty -E -q
    programMessage "${packageName} started"
  fi
}

performAction_stop() {
  eval "${noMoreParameters}"

  makeDirectories
  setBrailleParameters

  [ -f "${BRLTTY_PID_FILE}" ] || semanticError "${packageName} not running"

  export BRLTTY_LOG_FILE="${BRLTTY_LOG_FILE}.stop"
  brltty -E -C -q

  local timeout=50

  while [ -f "${BRLTTY_PID_FILE}" ]
  do
    let "timeout -= 1" || {
      programMessage "stop timed out"
      exit 3
    }

    sleep 0.1
  done

  programMessage "${packageName} stopped"
}

[ "${#}" -gt 0 ] || syntaxError "missing action"
action="${1}"
shift 1

case "${action}"
in
  start|stop) "performAction_${action}" "${@}";;
  *) syntaxError "unknown action: ${action}";;
esac

exit 0
