#!/bin/bash -p

set -e
cd "$(dirname "${0}")"

cd brltty
./autogen

./configure \
   --host=arm-none-linux-gnueabi \
   --enable-relocatable-install \
   --enable-standalone-programs \
   \
   --disable-api \
   --disable-gpm \
   --disable-iconv \
   --disable-icu \
   --disable-x \
   \
   --with-text-table=en-nabcc \
   --with-attributes-table=upper_lower \
   --with-braille-driver=bg,-all \
   --disable-speech-support \
   --with-screen-driver=lx,-all \
   \
   --without-pgmpath-package \
   --without-service-package \
   --without-params-package \
   --without-dynld-package \
   --without-charset-package \
   --without-mntpt-package \
   --without-mntfs-package \
   --without-bell-package \
   --without-leds-package \
   --without-beep-package \
   --with-pcm-package=oss \
   --without-midi-package \
   --without-fm-package \
   --without-serial-package \
   --without-usb-package \
   --without-bluetooth-package \
   --without-ports-package \
   \
   --disable-java-bindings \
   --disable-ocaml-bindings \
   --disable-python-bindings \
   --disable-tcl-bindings \
   \
   --quiet \
   "${@}"

exit "${?}"
