#!/bin/sh

set -e
cd "$(dirname "${0}")"

putFile() {
  local from="${1}"
  local to="${2}"
  local toMode="${3}"

  [ "${to%/}" = "${to}" ] || to="${to}/${from##*/}"
  adb push "${from}" "${to}"
  adb shell chmod "a=${toMode},u+w" "${to}"
}

putData() {
  local from="${1}"
  local to="${2}"

  putFile "${from}" "${to}" r
}

putProgram() {
  local from="${1}"
  local to="${2}"

  putFile "${from}" "${to}" rx
}

(
  set -e
  cd brltty/Programs
  make -s brltty
  putProgram brltty /sbin/
)

adb shell mkdir -p /etc/brltty/Input/bg
putData brltty.prefs /etc/brltty/prefs.template
putData brltty/Tables/Input/chords.kti /etc/brltty/Input/
putData brltty/Tables/Input/toggle.kti /etc/brltty/Input/
putData brltty/Tables/Input/bg/all.ktb /etc/brltty/Input/bg/
adb shell chmod -R go-w /etc/brltty

putProgram braille /sbin/
putProgram shell /sbin/

exit 0
