#!/bin/sh

set -e
cd "$(dirname "${0}")"

putFile() {
  local fromFile="${1}"
  local toDirectory="${2}"
  local toMode="${3}"

  local toFile="${toDirectory}/${fromFile##*/}"
  adb push "${fromFile}" "${toFile}"
  adb shell chmod "a=${toMode},u+w" "${toFile}"
}

putData() {
  local fromFile="${1}"
  local toDirectory="${2}"

  putFile "${fromFile}" "${toDirectory}" r
}

putProgram() {
  local fromFile="${1}"
  local toDirectory="${2}"

  putFile "${fromFile}" "${toDirectory}" rx
}

(
  set -e
  cd brltty/Programs
  make -s brltty
  putProgram brltty /sbin/
)

adb shell mkdir -p /etc/brltty/Input/bg
putData brltty/Tables/Input/chords.kti /etc/brltty/Input/
putData brltty/Tables/Input/toggle.kti /etc/brltty/Input/
putData brltty/Tables/Input/bg/all.ktb /etc/brltty/Input/bg/
adb shell chmod -R go-w /etc/brltty

putProgram braille /sbin/
putProgram shell /sbin/

exit 0
