include ../setup.mk
include $(BUILD_DIRECTORY)app.prologue.mk

APPLICATION_NAME = NBP_Common
PACKAGE_PATH = org.nbp.common

NATIVE_SOURCES += java.h
NATIVE_SOURCES += files.c

include $(BUILD_DIRECTORY)app.epilogue.mk
