include ../../setup.mk
include $(BUILD_DIRECTORY)doc.prologue.mk
include $(BUILD_DIRECTORY)doc.properties.mk

DOCUMENT_NAMES += QuickStart
DOCUMENT_NAMES += UserInterface
DOCUMENT_NAMES += index

include $(BUILD_DIRECTORY)doc.epilogue.mk
