#!/bin/sh
set -e

printProperty() {
  local name="${1}"
  local value="${2}"

  echo ".. |${name}| replace:: ${value}"
}

. ../../properties.sh

printProperty "package version" "${packageVersion}"
printProperty "source revision" "${sourceRevision}"
printProperty "build time" "${buildDate} ${buildTime} ${buildZone}"

exit 0
