#!/bin/sh
set -e

. ../application.sh
. ../../properties.sh
. ../../rst.sh

writeSubstitution "package version" "${versionNumber}"
writeSubstitution "source revision" "${sourceRevision}"
writeSubstitution "build time" "${buildDate} ${buildTime} ${buildZone}"

exit 0
