#!/bin/sh
set -e

printProperty() {
  local name="${1}"
  local format="${2}"
  shift 2

  printf ".. |${name}| replace:: ${format}\\n" "${@}"
}

. ../../revision.sh

printProperty "package version" "%d.%d.%d" "${versionMajor}" "${versionMinor}" "${revisionIncrement}"
printProperty "source revision" "git:%s" "${revisionCommit}"
printProperty "build time" "%s" "$(date --utc +'%Y-%m-%d %H:%M %Z')"

exit 0
