include ../setup.mk
include $(BUILD_DIRECTORY)app.prologue.mk
include $(BUILD_DIRECTORY)app.properties.mk

APPLICATION_NAME = NBP_Phone
PACKAGE_PATH = org.nbp.phone

include $(BUILD_DIRECTORY)app.epilogue.mk
