bind Space+Dots8+Dots135#o SaveSettings
bind Space+Dots7+Dots135#o RestoreSettings
bind Space+Dots78+Dots135#o ResetSettings

bind Forward+Space+Dot1 LogsOn
bind Forward+Space+Dot2 ClearAndroidLog
bind Forward+Space+Dot3 SendAndroidLog
bind Forward+Space+Dot7 LogsOff

bind Space+Dots78+Dot1#a LogActionsOn
bind Space+Dots78+Dot1#a+LongPress LogActionsOff

bind Space+Dots78+Dots1345#n LogNavigationOn
bind Space+Dots78+Dots1345#n+LongPress LogNavigationOff

bind Space+Dots78+Dots136#u LogUpdatesOn
bind Space+Dots78+Dots136#u+LongPress LogUpdatesOff

bind Space+Dots78+Dots13#k LogKeyboardOn
bind Space+Dots78+Dots13#k+LongPress LogKeyboardOff

bind Space+Dots78+Dots15#e LogEmulationsOn
bind Space+Dots78+Dots15#e+LongPress LogEmulationsOff

bind Space+Dots78+Dots12#b LogBrailleOn
bind Space+Dots78+Dots12#b+LongPress LogBrailleOff

bind Space+Dots78+Dots234#s LogSpeechOn
bind Space+Dots78+Dots234#s+LongPress LogSpeechOff

bind Space+Dots78+Dots1346#x+LongPress ForceCrash

