# make this one very hard to type by accident
bind Forward+Backward+Dots1245+LongPress DeveloperOn
bind Forward+Backward+Dots1245 DeveloperOff

bind Forward+Dots1237 LogsOff

bind Space+Dots78+Dots136#u LogUpdatesOn
bind Space+Dots78+Dots136#u+LongPress LogUpdatesOff
bind Space+Dots78+Dots13#k LogKeyboardOn
bind Space+Dots78+Dots13#k+LongPress LogKeyboardOff
bind Space+Dots78+Dot1#a LogActionsOn
bind Space+Dots78+Dot1#a+LongPress LogActionsOff
bind Space+Dots78+Dots1345#n LogNavigationOn
bind Space+Dots78+Dots1345#n+LongPress LogNavigationOff
bind Space+Dots78+Dots1245#g LogGesturesOn
bind Space+Dots78+Dots1245#g+LongPress LogGesturesOff
bind Space+Dots78+Dots12#b LogBrailleOn
bind Space+Dots78+Dots12#b+LongPress LogBrailleOff

bind Space+Dots78+Dots234#s SaveSettings
bind Space+Dots78+Dots1235#r RestoreSettings
bind Space+Dots78+Dots145#d ResetSettings

bind Space+Dots78+Dots1346#x ForceCrash

bind Forward+Space+Dot1 ClearAndroidLog
bind Forward+Space+Dot2 SendAndroidLog

