# make this one very hard to type by accident
bind Forward+Backward+Dots1245 DeveloperOff
bind Forward+Backward+Dots1245+LongPress DeveloperOn

bind Forward+Dots1237 LogsOff
bind Forward+Dot1 LogKeyboardOn
bind Forward+Dot2 LogActionsOn
bind Forward+Dot3 LogNavigationOn
bind Forward+Dot7 LogUpdatesOn

bind Forward+Dots12 SaveSettings
bind Forward+Dots23 RestoreSettings
bind Forward+Dots37 ResetSettings

bind Forward+Dots17 ForceCrash

bind Forward+Space+Dot1 ClearAndroidLog
bind Forward+Space+Dot2 SendAndroidLog

