# make this one very hard to type by accident
bind Forward+Backward+Dots1245 DeveloperOff
bind Forward+Backward+Dots1245+LongPress DeveloperOn

bind Forward+Dots1237 LogNone
bind Forward+Dot1 LogKeys
bind Forward+Dot2 LogActions
bind Forward+Dot3 LogNavigation
bind Forward+Dot7 LogUpdates

bind Forward+Dots12 SaveSettings
bind Forward+Dots23 RestoreSettings
bind Forward+Dots37 ResetSettings

bind Forward+Dots17 ForceCrash

