bind 8 Enter

bind B PanLeft
bind F PanRight

bind U ArrowUp
bind D ArrowDown
bind L ArrowLeft
bind R ArrowRight

bind 7X DescribeCharacter
bind 8X SetLeft

bind S148 CopyToClipboard

bind B1 BrailleInputOff
bind F4 BrailleInputOn

bind B3 LongPressOff
bind F6 LongPressOn

bind B7 OneHandOff
bind F8 OneHandOn

bind SBF DescribeBuild

bind S12345678 Null

include all-required.keys.inc
include all-legacy.keys.inc
include all-developer.keys.inc
