glyph	U+2500	 2356	# light horizontal
glyph	U+254C	 2356	# light double dash horizontal
glyph	U+2504	 2356	# light triple dash horizontal
glyph	U+2508	 2356	# light quadruple dash horizontal

glyph	U+2502	12345678	# light vertical
glyph	U+254E	12345678	# light double dash vertical
glyph	U+2506	12345678	# light triple dash vertical
glyph	U+250A	12345678	# light quadruple dash vertical

glyph	U+250C	 235678	# light down and right
glyph	U+2510	 235678	# light down and left
glyph	U+2514	123456	# light up and right
glyph	U+2518	123456	# light up and left
glyph	U+251C	12345678	# light vertical and right
glyph	U+2524	12345678	# light vertical and left
glyph	U+252C	 235678	# light down and horizontal
glyph	U+2534	123456	# light up and horizontal
glyph	U+253C	12345678	# light vertical and horizontal

glyph	U+2501	 2356	# heavy horizontal
glyph	U+254D	 2356	# heavy double dash horizontal
glyph	U+2505	 2356	# heavy triple dash horizontal
glyph	U+2509	 2356	# heavy quadruple dash horizontal

glyph	U+2503	12345678	# heavy vertical
glyph	U+254F	12345678	# heavy double dash vertical
glyph	U+2507	12345678	# heavy triple dash vertical
glyph	U+250B	12345678	# heavy quadruple dash vertical

glyph	U+250F	 235678	# heavy down and right
glyph	U+2513	 235678	# heavy down and left
glyph	U+2517	123456	# heavy up and right
glyph	U+251B	123456	# heavy up and left
glyph	U+2523	12345678	# heavy vertical and right
glyph	U+252B	12345678	# heavy vertical and left
glyph	U+2533	 235678	# heavy down and horizontal
glyph	U+253B	123456	# heavy up and horizontal
glyph	U+254B	12345678	# heavy vertical and horizontal

glyph	U+2550	 2356	# double horizontal
glyph	U+2551	12345678	# double vertical
glyph	U+2554	 235678	# double down and right
glyph	U+2557	 235678	# double down and left
glyph	U+255A	123456	# double up and right
glyph	U+255D	123456	# double up and left
glyph	U+2560	12345678	# double vertical and right
glyph	U+2563	12345678	# double vertical and left
glyph	U+2566	 235678	# double down and horizontal
glyph	U+2569	123456	# double up and horizontal
glyph	U+256C	12345678	# double vertical and horizontal

glyph	U+250D	 235678	# down light and right heavy
glyph	U+250E	 235678	# down heavy and right light
glyph	U+2511	 235678	# down light and left heavy
glyph	U+2512	 235678	# down heavy and left light
glyph	U+2515	123456	# up light and right heavy
glyph	U+2516	123456	# up heavy and right light
glyph	U+2519	123456	# up light and left heavy
glyph	U+251A	123456	# up heavy and left light

glyph	U+251D	12345678	# vertical light and right heavy
glyph	U+251E	12345678	# up heavy and right down light
glyph	U+251F	12345678	# down heavy and right up light
glyph	U+2520	12345678	# vertical heavy and right light
glyph	U+2521	12345678	# down light and right up heavy
glyph	U+2522	12345678	# up light and right down heavy
glyph	U+2525	12345678	# vertical light and left heavy
glyph	U+2526	12345678	# up heavy and left down light
glyph	U+2527	12345678	# down heavy and left up light
glyph	U+2528	12345678	# vertical heavy and left light
glyph	U+2529	12345678	# down light and left up heavy
glyph	U+252A	12345678	# up light and left down heavy
glyph	U+252D	 235678	# left heavy and right down light
glyph	U+252E	 235678	# right heavy and left down light
glyph	U+252F	 235678	# down light and horizontal heavy
glyph	U+2530	 235678	# down heavy and horizontal light
glyph	U+2531	 235678	# right light and left down heavy
glyph	U+2532	 235678	# left light and right down heavy
glyph	U+2535	123456	# left heavy and right up light
glyph	U+2536	123456	# right heavy and left up light
glyph	U+2537	123456	# up light and horizontal heavy
glyph	U+2538	123456	# up heavy and horizontal light
glyph	U+2539	123456	# right light and left up heavy
glyph	U+253A	123456	# left light and right up heavy
glyph	U+253D	12345678	# left heavy and right vertical light
glyph	U+253E	12345678	# right heavy and left vertical light
glyph	U+253F	12345678	# vertical light and horizontal heavy
glyph	U+2540	12345678	# up heavy and down horizontal light
glyph	U+2541	12345678	# down heavy and up horizontal light
glyph	U+2542	12345678	# vertical heavy and horizontal light
glyph	U+2543	12345678	# left up heavy and right down light
glyph	U+2544	12345678	# right up heavy and left down light
glyph	U+2545	12345678	# left down heavy and right up light
glyph	U+2546	12345678	# right down heavy and left up light
glyph	U+2547	12345678	# down light and up horizontal heavy
glyph	U+2548	12345678	# up light and down horizontal heavy
glyph	U+2549	12345678	# right light and left vertical heavy
glyph	U+254A	12345678	# left light and right vertical heavy

glyph	U+2552	 235678	# down single and right double
glyph	U+2553	 235678	# down double and right single
glyph	U+2555	 235678	# down single and left double
glyph	U+2556	 235678	# down double and left single
glyph	U+2558	123456	# up single and right double
glyph	U+2559	123456	# up double and right single
glyph	U+255B	123456	# up single and left double
glyph	U+255C	123456	# up double and left single
glyph	U+255E	12345678	# vertical single and right double
glyph	U+255F	12345678	# vertical double and right single
glyph	U+2561	12345678	# vertical single and left double
glyph	U+2562	12345678	# vertical double and left single
glyph	U+2564	 235678	# down single and horizontal double
glyph	U+2565	 235678	# down double and horizontal single
glyph	U+2567	123456	# up single and horizontal double
glyph	U+2568	123456	# up double and horizontal single
glyph	U+256A	12345678	# vertical single and horizontal double
glyph	U+256B	12345678	# vertical double and horizontal single

glyph	U+256D	 235678	# light arc down and right
glyph	U+256E	 235678	# light arc down and left
glyph	U+256F	123456	# light arc up and left
glyph	U+2570	123456	# light arc up and right

glyph	U+2574	 2356	# light left
glyph	U+2575	123456	# light up
glyph	U+2576	 2356	# light right
glyph	U+2577	 235678	# light down
glyph	U+2578	 2356	# heavy left
glyph	U+2579	123456	# heavy up
glyph	U+257A	 2356	# heavy right
glyph	U+257B	 235678	# heavy down

glyph	U+257C	 2356	# light left and heavy right
glyph	U+257D	12345678	# light up and heavy down
glyph	U+257E	 2356	# heavy left and light right
glyph	U+257F	12345678	# heavy up and light down

glyph	U+2571	   47	# light diagonal upper right to lower left
glyph	U+2572	18	# light diagonal upper left to lower right
glyph	U+2573	1478	# light diagonal cross

