char	ç	123468	# lowercase c cedilla
char	é	1234568	# lowercase e acute
char	à	123568	# lowercase a grave
char	è	23468	# lowercase e grave
char	ù	234568	# lowercase u grave
char	â	168	# lowercase a circumflex
char	ê	1268	# lowercase e circumflex
char	î	1468	# lowercase i circumflex
char	ô	14568	# lowercase o circumflex
char	û	1568	# lowercase u circumflex
char	ë	12468	# lowercase e diaeresis
char	ï	124568	# lowercase i diaeresis

char	Ç	1234678	# uppercase c cedilla
char	É	12345678	# uppercase e acute
char	À	1235678	# uppercase a grave
char	È	234678	# uppercase e grave
char	Ù	2345678	# uppercase u grave
char	Â	1678	# uppercase a circumflex
char	Ê	12678	# uppercase e circumflex
char	Î	14678	# uppercase i circumflex
char	Ô	145678	# uppercase o circumflex
char	Û	15678	# uppercase u circumflex
char	Ë	124678	# uppercase e diaeresis
char	Ï	1245678	# uppercase i diaeresis

