include letters-latin.chars.inc
include numbers-french.chars.inc

char	space	0
char	!	235
char	"	2356
char	\#	34568
char	$	357
char	%	3468
char	&	1234568
char	'	3
char	(	236
char	)	356

char	*	35
char	+	23578
char	,	2
char	-	36
char	.	256
char	/	34

char	:	25
char	;	23
char	<	238
char	=	235678
char	>	567
char	?	26

char	@	345
char	[	23678
char	\\	348
char	]	35678
char	^	4
char	_	578

char	`	6
char	{	2378
char	|	4568
char	}	5678
char	~	38

char	U+00A1	2358	# inverted exclamation mark
char	U+00A2	1478	# cent sign
char	U+00A3	237	# pound sign
char	U+00A4	45	# currency sign
char	U+00A5	25678	# yen sign
char	U+00A6	458	# broken bar
char	U+00A7	12348	# section sign
char	U+00A8	46	# diaeresis
char	U+00A9	148	# copyright sign
char	U+00AA	1678	# feminine ordinal indicator
char	U+00AB	23568	# left-pointing double angle quotation mark
char	U+00AC	2567	# not sign
char	U+00AD	78	# soft hyphen
char	U+00AE	12358	# registered sign
char	U+00AF	1348	# macron
char	U+00B0	267	# degree sign
char	U+00B1	3678	# plus-minus sign
char	U+00B2	457	# superscript two
char	U+00B3	4567	# superscript three
char	U+00B4	5	# acute accent
char	U+00B5	257	# micro sign
char	U+00B6	45678	# pilcrow sign
char	U+00B7	8	# middle dot
char	U+00B8	456	# cedilla
char	U+00B9	47	# superscript one
char	U+00BA	2678	# masculine ordinal indicator
char	U+00BB	23567	# right-pointing double angle quotation mark
char	U+00BC	1368	# vulgar fraction one quarter
char	U+00BD	468	# vulgar fraction one half
char	U+00BE	13468	# vulgar fraction three quarters
char	U+00BF	268	# inverted question mark

char	U+00C0	123567	# latin capital letter a with grave
char	U+00C1	1235678	# latin capital letter a with acute
char	U+00C2	167	# latin capital letter a with circumflex
char	U+00C3	178	# latin capital letter a with tilde
char	U+00C4	34567	# latin capital letter a with diaeresis
char	U+00C5	27	# latin capital letter a with ring above
char	U+00C6	3457	# latin capital letter ae
char	U+00C7	123467	# latin capital letter c with cedilla
char	U+00C8	23467	# latin capital letter e with grave
char	U+00C9	1234567	# latin capital letter e with acute
char	U+00CA	1267	# latin capital letter e with circumflex
char	U+00CB	12467	# latin capital letter e with diaeresis
char	U+00CC	2478	# latin capital letter i with grave
char	U+00CD	347	# latin capital letter i with acute
char	U+00CE	1467	# latin capital letter i with circumflex
char	U+00CF	124567	# latin capital letter i with diaeresis
char	U+00D0	1278	# latin capital letter eth
char	U+00D1	134578	# latin capital letter n with tilde
char	U+00D2	13578	# latin capital letter o with grave
char	U+00D3	3467	# latin capital letter o with acute
char	U+00D4	14567	# latin capital letter o with circumflex
char	U+00D5	1378	# latin capital letter o with tilde
char	U+00D6	24678	# latin capital letter o with diaeresis
char	U+00D7	3578	# multiplication sign
char	U+00D8	345678	# latin capital letter o with stroke
char	U+00D9	234567	# latin capital letter u with grave
char	U+00DA	2345678	# latin capital letter u with acute
char	U+00DB	1567	# latin capital letter u with circumflex
char	U+00DC	12567	# latin capital letter u with diaeresis
char	U+00DD	1345678	# latin capital letter y with acute
char	U+00DE	24578	# latin capital letter thorn
char	U+00DF	2348	# latin small letter sharp s

char	U+00E0	12356	# latin small letter a with grave
char	U+00E1	123568	# latin small letter a with acute
char	U+00E2	168	# latin small letter a with circumflex
char	U+00E3	18	# latin small letter a with tilde
char	U+00E4	34578	# latin small letter a with diaeresis
char	U+00E5	28	# latin small letter a with ring above
char	U+00E6	3458	# latin small letter ae
char	U+00E7	12346	# latin small letter c with cedilla
char	U+00E8	2346	# latin small letter e with grave
char	U+00E9	123456	# latin small letter e with acute
char	U+00EA	1268	# latin small letter e with circumflex
char	U+00EB	12468	# latin small letter e with diaeresis
char	U+00EC	248	# latin small letter i with grave
char	U+00ED	3478	# latin small letter i with acute
char	U+00EE	1468	# latin small letter i with circumflex
char	U+00EF	124568	# latin small letter i with diaeresis
char	U+00F0	128	# latin small letter eth
char	U+00F1	1245678	# latin small letter n with tilde
char	U+00F2	1358	# latin small letter o with grave
char	U+00F3	346	# latin small letter o with acute
char	U+00F4	14568	# latin small letter o with circumflex
char	U+00F5	4678	# latin small letter o with tilde
char	U+00F6	358	# latin small letter o with diaeresis
char	U+00F7	2578	# division sign
char	U+00F8	568	# latin small letter o with stroke
char	U+00F9	23456	# latin small letter u with grave
char	U+00FA	234568	# latin small letter u with acute
char	U+00FB	1568	# latin small letter u with circumflex
char	U+00FC	12568	# latin small letter u with diaeresis
char	U+00FD	134568	# latin small letter y with acute
char	U+00FE	2458	# latin small letter thorn
char	U+00FF	2568	# latin small letter y with diaeresis

char	U+20AC	1578	# euro sign
char	U+201A	67	# single low-9 quotation mark
char	U+0192	1248	# latin small letter f with hook
char	U+201E	56	# double low-9 quotation mark
char	U+2026	368	# horizontal ellipsis
char	U+2020	3568	# dagger
char	U+2021	3567	# double dagger
char	U+02C6	48	# modifier letter circumflex accent
char	U+2030	34678	# per mille sign
char	U+0160	234678	# latin capital letter s with caron
char	U+2039	57	# single left-pointing angle quotation mark
char	U+0152	2467	# latin capital ligature oe
char	U+017D	135678	# latin capital letter z with caron
char	U+2018	68	# left single quotation mark
char	U+2019	37	# right single quotation mark
char	U+201C	378	# left double quotation mark
char	U+201D	678	# right double quotation mark
char	U+2022	124578	# bullet
char	U+2013	478	# en dash
char	U+2014	4578	# em dash
char	U+02DC	467	# small tilde
char	U+2122	23458	# trade mark sign
char	U+0161	23468	# latin small letter s with caron
char	U+203A	58	# single right-pointing angle quotation mark
char	U+0153	2468	# latin small ligature oe
char	U+017E	13568	# latin small letter z with caron
char	U+0178	145678	# latin capital letter y with diaeresis

