# uppercase letters
glyph	U+0391	17	# uppercase alpha
glyph	U+0392	127	# uppercase beta
glyph	U+0393	12457	# uppercase gamma
glyph	U+0394	1457	# uppercase delta
glyph	U+0395	157	# uppercase epsilon
glyph	U+0396	13567	# uppercase zeta
glyph	U+0397	3457	# uppercase eta
glyph	U+0398	14567	# uppercase theta
glyph	U+0399	247	# uppercase iota
glyph	U+039A	137	# uppercase kappa
glyph	U+039B	1237	# uppercase lambda
glyph	U+039C	1347	# uppercase mu
glyph	U+039D	13457	# uppercase nu
glyph	U+039E	13467	# uppercase xi
glyph	U+039F	1357	# uppercase omicron
glyph	U+03A0	12347	# uppercase pi
glyph	U+03A1	12357	# uppercase rho
glyph	U+03A3	2347	# uppercase sigma
glyph	U+03A4	23457	# uppercase tau
glyph	U+03A5	134567	# uppercase upsilon
glyph	U+03A6	1247	# uppercase phi
glyph	U+03A7	1257	# uppercase chi
glyph	U+03A8	123467	# uppercase psi
glyph	U+03A9	2457	# uppercase omega

# lowercase letters
glyph	U+03B1	1	# lowercase alpha
glyph	U+03B2	12	# lowercase beta
glyph	U+03B3	1245	# lowercase gamma
glyph	U+03B4	145	# lowercase delta
glyph	U+03B5	15	# lowercase epsilon
glyph	U+03B6	1356	# lowercase zeta
glyph	U+03B7	345	# lowercase eta
glyph	U+03B8	1456	# lowercase theta
glyph	U+03B9	24	# lowercase iota
glyph	U+03BA	13	# lowercase kappa
glyph	U+03BB	123	# lowercase lambda
glyph	U+03BC	134	# lowercase mu
glyph	U+03BD	1345	# lowercase nu
glyph	U+03BE	1346	# lowercase xi
glyph	U+03BF	135	# lowercase omicron
glyph	U+03C0	1234	# lowercase pi
glyph	U+03C1	1235	# lowercase rho
glyph	U+03C2	234	# lowercase final sigma
glyph	U+03C3	234	# lowercase sigma
glyph	U+03C4	2345	# lowercase tau
glyph	U+03C5	13456	# lowercase upsilon
glyph	U+03C6	124	# lowercase phi
glyph	U+03C7	125	# lowercase chi
glyph	U+03C8	12346	# lowercase psi
glyph	U+03C9	245	# lowercase omega

# uppercase letters with tonos
glyph	U+0386	178	# uppercase alpha tonos
glyph	U+0388	1578	# uppercase epsilon tonos
glyph	U+0389	34578	# uppercase eta tonos
glyph	U+038A	2478	# uppercase iota tonos
glyph	U+038C	13578	# uppercase omicron tonos
glyph	U+038E	1345678	# uppercase upsilon tonos
glyph	U+038F	24578	# uppercase omega tonos

# lowercase letters with tonos
glyph	U+03AC	18	# lowercase alpha tonos
glyph	U+03AD	158	# lowercase epsilon tonos
glyph	U+03AE	3458	# lowercase eta tonos
glyph	U+03AF	248	# lowercase iota tonos
glyph	U+03CC	1358	# lowercase omicron tonos
glyph	U+03CD	134568	# lowercase upsilon tonos
glyph	U+03CE	2458	# lowercase omega tonos

# lowercase letters with Ypogegrammeni
glyph	U+1FB3	35	# lowercase alpha ypogegrammeni
glyph	U+1FC3	3456	# lowercase eta ypogegrammeni
glyph	U+1FF3	2456	# lowercase omega ypogegrammeni

# accents
glyph	U+1FEF	4	# varia
glyph	U+0384	5	# tonos
glyph	U+1FFD	5	# oxia
glyph	U+1FC0	6	# perispomeni
glyph	U+1FFE	1236	# dasia
glyph	U+1FCD	23456	# psili varia
glyph	U+1FCE	356	# psili oxia
glyph	U+1FCF	256	# psili perispomeni
glyph	U+1FDD	12356	# dasia varia
glyph	U+1FDE	26	# dasia oxia
glyph	U+1FDF	235	# dasia perispomeni

# punctuation
glyph	U+037E	26	# question mark
glyph	U+0387	23	# ano teleia

