# points
glyph	U+05B1	26	# hataf segol
glyph	U+05B2	25	# hataf patah
glyph	U+05B3	345	# hataf qamats
glyph	U+05B4	24	# hiriq
glyph	U+05B5	34	# tsere
glyph	U+05B6	15	# segol
glyph	U+05B7	14	# patah
glyph	U+05B8	126	# qamats
glyph	U+05B9	135	# holam
glyph	U+05BB	136	# qubuts

# letters
glyph	U+05D0	1	# alef
glyph	U+05D1	1236	# bet
glyph	U+05D2	1245	# gimel
glyph	U+05D3	145	# dalet
glyph	U+05D4	125	# he
glyph	U+05D5	2456	# vav
glyph	U+05D6	1356	# zayin
glyph	U+05D7	1346	# het
glyph	U+05D8	2345	# tet
glyph	U+05D9	245	# yod
glyph	U+05DA	168	# final kaf
glyph	U+05DB	16	# kaf
glyph	U+05DC	123	# lamed
glyph	U+05DD	1348	# final mem
glyph	U+05DE	134	# mem
glyph	U+05DF	13458	# final nun
glyph	U+05E0	1345	# nun
glyph	U+05E1	234	# samekh
glyph	U+05E2	1246	# ayin
glyph	U+05E3	1248	# final pe
glyph	U+05E4	1234	# pe
glyph	U+05E5	23468	# final tsadi
glyph	U+05E6	2346	# tsadi
glyph	U+05E7	12345	# qof
glyph	U+05E8	1235	# resh
glyph	U+05E9	146	# shin
glyph	U+05EA	1456	# tav

# accented letters
glyph	U+FB1D	35	# yod hiriq
glyph	U+FB2A	146	# shin shin-dot
glyph	U+FB2B	156	# shin sin-dot
glyph	U+FB31	12	# bet dagesh
glyph	U+FB35	346	# vav dagesh
glyph	U+FB3A	13	# final kaf dagesh
glyph	U+FB3B	13	# kaf dagesh
glyph	U+FB43	1234	# final pe dagesh
glyph	U+FB44	1234	# pe dagesh
glyph	U+FB4A	1256	# tav dagesh

