bind Cursor BringCursor

bind Dot7 DeletePrevious
bind Space+Dots145#d DeleteNext

bind Backward+Cursor SetSelectionStart
bind Forward+Cursor SetSelectionEnd
bind Space+Dot8+Dot1#a SelectAll

bind Space+Dot8+Dots1346#x CutToClipboard
bind Space+Dot8+Dots1236#v PasteFromClipboard

bind Space+Dot7 TypeDot7
bind Space+Dot8 TypeDot8

bind Space+Dots136#u TypeUnicode
bind Space+Dots1346#x TypeControl

bind Space+Dots17 ToSelectionStart
bind Space+Dots48 ToSelectionEnd

bind Space+Dot7+Dots2345#t TypingModeText
bind Space+Dot8+Dots2345#t TypingModeBraille
bind Space+Dots78+Dots2345#t TypingModeConfirm

bind Space+Dot7+Dots125#h ResetHighlightedTyping
bind Space+Dot7+Dots12#b TypingBoldOff
bind Space+Dot8+Dots12#b TypingBoldOn
bind Space+Dot7+Dots24#i TypingItalicOff
bind Space+Dot8+Dots24#i TypingItalicOn
bind Space+Dot7+Dots136#u TypingUnderlineOff
bind Space+Dot8+Dots136#u TypingUnderlineOn

