char	é	1234568	# lowercase a acute
char	à	123568	# lowercase a grave
char	è	23468	# lowercase e grave
char	ì	348	# lowercase i grave
char	ò	3468	# lowercase o grave
char	ù	234568	# lowercase u grave

char	É	12345678	# uppercase a acute
char	À	1235678	# uppercase a grave
char	È	234678	# uppercase e grave
char	Ì	3478	# uppercase i grave
char	Ò	34678	# uppercase o grave
char	Ù	2345678	# uppercase u grave

