bind Space+Dot3 CursorLeft
bind Space+Dot6 CursorRight
bind Space+Dots36 SayCharacter

bind Space+Dot2 ToPreviousWord
bind Space+Dot5 ToNextWord
bind Space+Dots25 SayWord
bind Space+Dots25+LongPress SpellWord

bind Space+Dot1 CursorUp
bind Space+Dot4 CursorDown
bind Space+Dots14 SayLine

bind Space+Dots23 PageUp
bind Space+Dots56 PageDown

bind Space+Dots13 Home
bind Space+Dots46 End

bind Space+Dots12 TabBackward
bind Space+Dots45 TabForward

