include letters-latin.chars.inc
include numbers-nemeth.chars.inc

char space 0
char ! 2346
char " 5
char # 3456
char $ 1246
char % 146
char & 12346
char ' 3
char ( 12356
char ) 23456
char * 16
char + 346
char , 6
char - 36
char . 46
char / 34

char : 156
char ; 56
char < 126
char = 123456
char > 345
char ? 1456

char ` 4
char { 246
char | 1256
char } 12456
char ~ 45
char _ 456

char @ 47
char [ 2467
char \ 12567
char ] 124567
char ^ 457

