bind Backward+LongPress MoveBackward
bind Forward+LongPress MoveForward

bind Backward+Space MoveBackward
bind Forward+Space MoveForward

bind Center Click
bind Space+Center LongClick

bind Dot4+Up Notifications
bind Dot4+Down HomeKey
bind Dot4+Left BackKey
bind Dot4+Right RecentApps
bind Dot4+Center MenuKey

bind Space+Dots1345#n Notifications
bind Space+Dots123456 HomeKey
bind Space+Dots1356#z BackKey
bind Space+Dots1235#r RecentApps
bind Space+Dots134#m MenuKey

bind Space+Dots124#f FindForward
bind Space+Dot7+Dots124#f FindPrevious
bind Space+Dot8+Dots124#f FindNext

bind Space+Dots1245#g Guide
bind Space+Dots135#o Settings
bind Space+Dots1234#p PowerOff
bind Space+Dots2345#t Clock
bind Space+Dots1246#ed Editor
bind Space+Dots1456#? Assist

bind Space+Dots234#s,Space AndroidSettings
bind Space+Dots234#s,Dot1#a AndroidAccessibilitySettings
bind Space+Dots234#s,Dots12#b AndroidBluetoothSettings
bind Space+Dots234#s,Dots2456#w AndroidWifiSettings

include developer-screen.keys.inc
