bind Backward+LongPress MoveBackward
bind Forward+LongPress MoveForward

bind Backward+Space MoveBackward
bind Forward+Space MoveForward

bind Space+Dots126 MoveToFirst
bind Space+Dots345 MoveToLast

bind Center Click
bind Space+Center LongClick

bind Dot4+Up Notifications
bind Dot4+Down HomeKey
bind Dot4+Left BackKey
bind Dot4+Right RecentApplications
bind Dot4+Center MenuKey

bind Space+Dots1345#n Notifications
bind Space+Dot7+Dots1345#n ShowNotificationsOff
bind Space+Dot8+Dots1345#n ShowNotificationsOn

bind Space+Dots123456 HomeKey
bind Space+Dots1356#z BackKey
bind Space+Dots1235#r RecentApplications
bind Space+Dots134#m MenuKey

bind Space+Dots124#f FindForward
bind Space+Dot7+Dots124#f FindPrevious
bind Space+Dot8+Dots124#f FindNext

bind Space+Dots125#h,Dots123#l ListActions
bind Space+Dots125#h,Dots134#m UserManualText
bind Space+Dots125#h,Dots12345#q QuickStartText
bind Space+Dots125#h,Dots1236#v VoiceOverText
bind Space+Dots125#h,Dots2456#w WarrantyText
bind Space+Dots125#h,Dots123456 ProductPage
bind Space+Dots125#h,Dots78+Dots134#m UserManualHTML
bind Space+Dots125#h,Dots78+Dots12345#q QuickStartHTML
bind Space+Dots125#h,Dots78+Dots1236#v VoiceOverHTML
bind Space+Dots125#h,Dots78+Dots2456#w WarrantyHTML
bind Space+Cursor ListCursorKeyActions

bind Space+Dots135#o Settings
bind Space+Dots78+Dots134#m Maintenance

bind Space+Dots1234#p PowerOff
bind Space+Dot7+Dots1234#p AirplaneModeOff
bind Space+Dot8+Dots1234#p AirplaneModeOn

bind Space+Dots2345#t Clock
bind Space+Dots1246#ed Editor
bind Space+Dots1456#? Assist

bind Space+Dots234#s,Dot1#a AccessibilitySettings
bind Space+Dots234#s,Dots12#b BluetoothSettings
bind Space+Dots234#s,Dots14#c Calendar
bind Space+Dots234#s,Dots145#d Dialer
bind Space+Dots234#s,Dots15#e EMail
bind Space+Dots234#s,Dots124#f FileManager
bind Space+Dots234#s,Dots1245#g Gallery
bind Space+Dots234#s,Dots134#m MusicPlayer
bind Space+Dots234#s,Dots78+Dots134#m MusicPlayPause
bind Space+Dots234#s,Dots7+Dots134#m MusicPrevious
bind Space+Dots234#s,Dots8+Dots134#m MusicNext
bind Space+Dots234#s,Dots1234#p People
bind Space+Dots234#s,Dots234#s AndroidSettings
bind Space+Dots234#s,Dots34#st Store
bind Space+Dots234#s,Dots2345#t TextMessaging
bind Space+Dots234#s,Dots1236#v VoiceCommand
bind Space+Dots234#s,Dots2456#w WifiSettings
bind Space+Dots234#s,Dots3456## Calculator

bind Space+Dot8+Dots123456#home AddShortcut
bind Space+Dot7+Dots123456#home RemoveShortcut

bind Dot5+Left DragLeft
bind Dot5+Right DragRight
bind Dot5+Up DragUp
bind Dot5+Down DragDown
bind Dot5+Center DragFrom

bind Dot6+Left DropLeft
bind Dot6+Right DropRight
bind Dot6+Up DropAbove
bind Dot6+Down DropBelow
bind Dot6+Center DropOn

bind Backward+Forward+Space DescribeBuild
bind Space+Dots1236#v DescribeBuild

include advanced-screen.keys.inc
