char	space	0

alias	nbsp	space	# no-break space
alias	nnbsp	space	# narrow no-break space
alias	znbsp	space	# zero-width no-break space

alias	U+1361	space	# ethiopic wordspace
alias	U+2002	space	# en space
alias	U+2003	space	# em space
alias	U+2004	space	# three-per-em space
alias	U+2005	space	# four-per-em space
alias	U+2006	space	# six-per-em space
alias	U+2009	space	# thin space
alias	U+200A	space	# hair space
alias	U+200B	space	# zero width space
alias	U+205F	space	# medium mathematical space
alias	U+3000	space	# ideographic space
