char	á	123568	# lowercase a acute
char	é	23468	# lowercase e acute
char	í	348	# lowercase i acute
char	ó	3468	# lowercase o acute
char	ú	234568	# lowercase u acute
char	ë	12468	# lowercase e diaeresis
char	ü	12568	# lowercase u diaeresis
char	ñ	124568	# lowercase n tilde

char	Á	1235678	# uppercase a acute
char	É	234678	# uppercase e acute
char	Í	3478	# uppercase i acute
char	Ó	34678	# uppercase o acute
char	Ú	2345678	# uppercase u acute
char	Ë	124678	# uppercase e diaeresis
char	Ü	125678	# uppercase u diaeresis
char	Ñ	1245678	# uppercase n tilde

char	¡	23467	# inverted exclamation point
char	¿	14567	# inverted question mark

