bind Space+VolumeDown SpeechOff
bind Space+VolumeUp SpeechOn

bind Forward+VolumeDown StopSpeaking
bind Forward+VolumeUp SayLine

bind Backward+VolumeDown SleepTalkOff
bind Backward+VolumeUp SleepTalkOn

bind Dot1+VolumeDown SpeakSofter
bind Dot1+VolumeUp SpeakLouder

bind Dot2+VolumeDown SpeakSlower
bind Dot2+VolumeUp SpeakFaster

bind Dot3+VolumeDown SpeakLower
bind Dot3+VolumeUp SpeakHigher

bind Dot4+VolumeDown SpeakLeft
bind Dot4+VolumeUp SpeakRight

