bind Forward+VolumeDown SpeechOff
bind Forward+VolumeUp SpeechOn

bind Backward+VolumeDown SleepTalkOff
bind Backward+VolumeUp SleepTalkOn

bind Dot1+Left StopSpeaking
bind Dot1+Right SayLine
bind Dot1+Up SayBefore
bind Dot1+Down SayAfter
bind Dot1+Center SayAll

bind Dot1+VolumeDown SpeakSofter
bind Dot1+VolumeUp SpeakLouder

bind Dot2+VolumeDown SpeakSlower
bind Dot2+VolumeUp SpeakFaster

bind Dot3+VolumeDown SpeakLower
bind Dot3+VolumeUp SpeakHigher

bind Dot4+VolumeDown SpeakLeft
bind Dot4+VolumeUp SpeakRight

bind Dot5+VolumeDown SleepTalkOff
bind Dot5+VolumeUp SleepTalkOn

bind Dot6+VolumeDown SpeechOff
bind Dot6+VolumeUp SpeechOn

include speech-keyboard.keys.inc
