char	©	148	# copyright
char	°	1458	# degree
char	€	158	# euro
char	µ	1348	# micro
char	¬	13458	# not
char	¶	12348	# paragraph (pilcrow)
char	®	12358	# registered
char	§	2348	# section
char	™	23458	# trademark
char	¥	134568	# yen

char	£	34567	# pound
char	¢	12467	# cent

char	·	467	# middle dot, bullet
char	«	123567	# left-pointing double angle quotation mark
char	»	234567	# right-pointing double angle quotation mark

char	±	3467	# plus-minus
alias	−	-	# minus
char	×	167	# multiplication
char	÷	347	# division
char	≠	1234567	# not equal
char	≤	3457	# less than or equal
char	≥	1267	# greater than or equal

char	⁰	3567	# superscript zero
char	¹	27	# superscript one
char	²	237	# superscript two
char	³	257	# superscript three
char	⁴	2567	# superscript four
char	⁵	267	# superscript five
char	⁶	2357	# superscript six
char	⁷	23567	# superscript seven
char	⁸	2367	# superscript eight
char	⁹	357	# superscript nine

char	₀	3568	# subscript zero
char	₁	28	# subscript one
char	₂	238	# subscript two
char	₃	258	# subscript three
char	₄	2568	# subscript four
char	₅	268	# subscript five
char	₆	2358	# subscript six
char	₇	23568	# subscript seven
char	₈	2368	# subscript eight
char	₉	358	# subscript nine

